name: tradutor_multilingue
description: Tradutor MÃºltiplo em Flutter
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2

flutter:
  uses-material-design: true
